[package]
name = "xmz_mod_touch_gui"
version = "0.7.0"
authors = ["Stefan Müller <s.mueller@it.kls-glt.de>"]

[dependencies]
gtk = { git = "https://github.com/gtk-rs/gtk", features = ["v3_16"] }
gdk = { git = "https://github.com/gtk-rs/gdk" }
pango = { git = "https://github.com/gtk-rs/pango" }
