[package]
name = "xmz_mod_touch_gui"
version = "0.9.0"
authors = ["Stefan Müller <s.mueller@it.kls-glt.de>"]
description = "xMZ-Mod-Touch GUI"
documentation = "https://gaswarnanlagen.com/xmz-mod-touch"
homepage = "https://gaswarnanlagen.com/xmz-mod-touch"
repository = "https://github.com/zzeroo/xMZ-Mod-Touch-GUI.git"
license = "GPL-2.0"

[dependencies.gtk]
version = "0.1.0"
features = ["v3_16"]

[dependencies]
gdk = "0.5.0"
glib = "0.1.0"
gtk-sys = "0.3.1"
libc = "0.2"
nanomsg = { git = "https://github.com/thehydroimpulse/nanomsg.rs.git" }
pango-sys = "0.3.1"
rustc-serialize = "0.3"
xmz_server = { git = "https://github.com/Kliemann-Service-GmbH/xMZ-Mod-Touch-Server.git", branch = "v0.5.x", version = "0.5.0" }
