[package]
name = "gtk-stack-swipe"
version = "0.1.0"
authors = ["Stefan Müller <s.mueller@it.kls-glt.de>"]

[dependencies]
gtk = { git = "https://github.com/gtk-rs/gtk", features = ["v3_14"] }
gdk = { git = "https://github.com/gtk-rs/gdk" }
