[package]
name = "xmz_mod_touch_gui"
version = "0.21.3"
authors = ["Stefan Müller <s.mueller@it.kls-glt.de>"]
description = "Grafische Oberfläche der 'xMZ-Mod-Touch'-Platform"
documentation = "https://gaswarnanlagen.com/xmz-mod-touch"
homepage = "https://gaswarnanlagen.com/xmz-mod-touch"
repository = "https://github.com/zzeroo/xMZ-Mod-Touch-GUI.git"
license = "GPL-2.0"

[[bin]]
name = "xmz_mod_touch_gui"
path = "src/main.rs"
doc = false

[features]
development = []

[dependencies]
env_logger = "0.3"
error-chain = "0.4"
gdk = "0.5.1"
glib = "0.1.1"
gtk = "0.1.1"
hyper = "0.10"
libc = "0.2.18"
log = "0.3"
rand = "0.3"
serde = "0.9"
serde_json = "0.9"
xmz_server = { git = "https://github.com/Kliemann-Service-GmbH/xMZ-Mod-Touch-Server.git" }
# xmz_server = { path = "../xMZ-Mod-Touch-Server"}
gobject-sys = "0.3.2"
gtk-sys = "0.3.2"

# Aktiviere Log in Tests: https://github.com/rust-lang-nursery/log#in-tests
[dev-dependencies]
env_logger = "0.3"
