[package]
name = "xmz_mod_touch_gui"
version = "0.14.0"
authors = ["Stefan Müller <s.mueller@it.kls-glt.de>"]
description = "Grafische Oberfläche der 'xMZ-Mod-Touch'-Platform"
documentation = "https://gaswarnanlagen.com/xmz-mod-touch"
homepage = "https://gaswarnanlagen.com/xmz-mod-touch"
repository = "https://github.com/zzeroo/xMZ-Mod-Touch-GUI.git"
license = "GPL-2.0"

[[bin]]
name = "xmz_mod_touch_gui"
path = "src/main.rs"
doc = false

[dependencies]
env_logger = "0.3"
error-chain = "0.4"
gdk = { version = "0.5.0" }
glib = "*"
gtk = { version = "0.1.0", features = ["v3_16"] }
libc = "0.2"
log = "0.3"
nanomsg = { git = "https://github.com/thehydroimpulse/nanomsg.rs.git" }
rand = "*"
rustc-serialize = "0.3"
xmz_client = { git = "https://github.com/Kliemann-Service-GmbH/xMZ-Mod-Touch-Client.git" }
#xmz_client = { path = "../xMZ-Mod-Touch-Client/" }
xmz_server = { git = "https://github.com/Kliemann-Service-GmbH/xMZ-Mod-Touch-Server.git" }
#xmz_server = { path = "../xMZ-Mod-Touch-Server/" }
# No Animation Gtk Hack
glib-sys = "*"
gtk-sys = "*"
gobject-sys = "*"

# Aktiviere Log in Tests: https://github.com/rust-lang-nursery/log#in-tests
[dev-dependencies]
env_logger = "0.3"
