[package]
name = "xmz_mod_touch_gui"
version = "0.32.0"
authors = ["Stefan Müller <s.mueller@it.kls-glt.de>"]
description = "Grafische Oberfläche der 'xMZ-Mod-Touch'-Platform"
documentation = "https://gaswarnanlagen.com/xmz-mod-touch"
homepage = "https://gaswarnanlagen.com/xmz-mod-touch"
repository = "https://github.com/zzeroo/xMZ-Mod-Touch-GUI.git"
license = "GPL-2.0"

[[bin]]
name = "xmz_mod_touch_gui"
path = "src/bin/xmz_mod_touch_gui.rs"
doc = false

[features]
development = []

[dependencies]
env_logger = "0.4"
gdk = "^0"
glib = "^0"
gobject-sys = "^0"
gtk = "^0"
gtk-sys = "^0"
hyper = "^0"
libc = "^0"
log = "0.3"
rand = "0.3"
serde = "0.9"
serde_json = "0.9"
xmz_mod_touch_server = { git = "https://github.com/Kliemann-Service-GmbH/xMZ-Mod-Touch-Server.git", version = "^0.32" }
# xmz_mod_touch_server = { path = "../xMZ-Mod-Touch-Server"}

# Aktiviere Log in Tests: https://github.com/rust-lang-nursery/log#in-tests
[dev-dependencies]
env_logger = "0.4"
