[package]
name = "xmz_mod_touch_gui"
version = "0.10.0"
authors = ["Stefan Müller <s.mueller@it.kls-glt.de>"]
description = "xMZ-Mod-Touch GUI"
documentation = "https://gaswarnanlagen.com/xmz-mod-touch"
homepage = "https://gaswarnanlagen.com/xmz-mod-touch"
repository = "https://github.com/zzeroo/xMZ-Mod-Touch-GUI.git"
license = "GPL-2.0"


[dependencies]
gtk = { version = "0.1.0", features = ["v3_16"] }
gdk = { version = "0.5.0" }
libc = "0.2"
nanomsg = { git = "https://github.com/thehydroimpulse/nanomsg.rs.git" }
rustc-serialize = "0.3"
xmz_client = { git = "https://github.com/Kliemann-Service-GmbH/xMZ-Mod-Touch-Client.git", branch = "master", version = ">=0.2.2" }
xmz_server = { git = "https://github.com/Kliemann-Service-GmbH/xMZ-Mod-Touch-Server.git", branch = "master", version = ">=0.5.0" }
