/* sensorwidget.c generated by valac 0.28.1, the Vala compiler
 * generated from sensorwidget.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <stdlib.h>
#include <string.h>
#include <stdio.h>


#define TYPE_SENSOR_WIDGET (sensor_widget_get_type ())
#define SENSOR_WIDGET(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_SENSOR_WIDGET, SensorWidget))
#define SENSOR_WIDGET_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_SENSOR_WIDGET, SensorWidgetClass))
#define IS_SENSOR_WIDGET(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_SENSOR_WIDGET))
#define IS_SENSOR_WIDGET_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_SENSOR_WIDGET))
#define SENSOR_WIDGET_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_SENSOR_WIDGET, SensorWidgetClass))

typedef struct _SensorWidget SensorWidget;
typedef struct _SensorWidgetClass SensorWidgetClass;
typedef struct _SensorWidgetPrivate SensorWidgetPrivate;

struct _SensorWidget {
	GtkStack parent_instance;
	SensorWidgetPrivate * priv;
};

struct _SensorWidgetClass {
	GtkStackClass parent_class;
};


static gpointer sensor_widget_parent_class = NULL;

GType sensor_widget_get_type (void) G_GNUC_CONST;
enum  {
	SENSOR_WIDGET_DUMMY_PROPERTY
};
SensorWidget* sensor_widget_new (void);
SensorWidget* sensor_widget_construct (GType object_type);
gint _vala_main (gchar** args, int args_length1);


SensorWidget* sensor_widget_construct (GType object_type) {
	SensorWidget * self = NULL;
	self = (SensorWidget*) g_object_new (object_type, NULL);
	return self;
}


SensorWidget* sensor_widget_new (void) {
	return sensor_widget_construct (TYPE_SENSOR_WIDGET);
}


static void sensor_widget_class_init (SensorWidgetClass * klass) {
	sensor_widget_parent_class = g_type_class_peek_parent (klass);
	gtk_widget_class_set_template_from_resource (GTK_WIDGET_CLASS (klass), "/com/gaswarnanlagen/xmz-mod-touch/sensorwidget.glade");
}


static void sensor_widget_instance_init (SensorWidget * self) {
	gtk_widget_init_template (GTK_WIDGET (self));
}


GType sensor_widget_get_type (void) {
	static volatile gsize sensor_widget_type_id__volatile = 0;
	if (g_once_init_enter (&sensor_widget_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (SensorWidgetClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) sensor_widget_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (SensorWidget), 0, (GInstanceInitFunc) sensor_widget_instance_init, NULL };
		GType sensor_widget_type_id;
		sensor_widget_type_id = g_type_register_static (gtk_stack_get_type (), "SensorWidget", &g_define_type_info, 0);
		g_once_init_leave (&sensor_widget_type_id__volatile, sensor_widget_type_id);
	}
	return sensor_widget_type_id__volatile;
}


gint _vala_main (gchar** args, int args_length1) {
	gint result = 0;
	FILE* _tmp0_ = NULL;
	_tmp0_ = stdout;
	fprintf (_tmp0_, "Up\n");
	result = 0;
	return result;
}


int main (int argc, char ** argv) {
#if !GLIB_CHECK_VERSION (2,35,0)
	g_type_init ();
#endif
	return _vala_main (argv, argc);
}



